### ISSUE TITLE
This is just a Test

### ISSUE THREAD

**Issue by TomMarvolo** [dariodf/FRSFBirds2015#1]
no le den bola XD
![c__data_users_defapps_appdata_internetexplorer_temp_saved images_hqdefault 1](https://cloud.githubusercontent.com/assets/7550985/8024672/388bcf5c-0d12-11e5-923b-8e504eb0e6de.jpg)

**Comment by prinsich** [comment]
Dejan de espamear
:v
[image: Inline image 1]

<name>Prinsich Bernz, Emilio J. A.</name>
<document>ISI - LU K18077 - DNI 33.218.707</document>
<organization>UTN - FRSF</organization>
